apiVersion: v1
data:
  GITHUB_REPOSITORY: bWluaXN0cnlvZmp1c3RpY2UvaG1wcHMtcHJvamVjdC1ib290c3RyYXA=
  GITHUB_TOKEN: Z2hwX2h1a0ZyTERuYWpKR3RYd0lzbjl6eXFPalp5MlB5UTJiR0NjYQ==
kind: Secret
metadata:
  name: hmpps-github-actions-runner
  namespace: hmpps-portfolio-management-dev
type: Opaque
