# https://docs.github.com/en/actions/creating-actions/creating-a-composite-action
name: Update quay.io with repository details
description: Uses service catalogue data to update quay.io
# Part of a collection of actions that will ultimately replace bootstrap.sh
runs:
  using: "composite"
  steps:
  - name: Checkout code
    uses: actions/checkout@v4
  - id: update-quayio
    name: update-quayio
    run: bash ./scripts/update-quayio.sh
    shell: bash
    env:
      GITHUB_REPO_NAME: ${{ env.github_repo_name }}
      GITHUB_ORG: "ministryofjustice"
      GITHUB_REPO_DESCRIPTION: "${{ env.github_repo_description }}"
      QUAYIO_ORG: "hmpps"
      QUAYIO_TOKEN: "${{ env.quayio_token }}"
      CIRCLECI_TOKEN: "${{ env.circleci_token }}"
