name: 'Remove offline runners'
description: 'action to remove offline runners'
inputs:
  gh_auth_token:
    description: 'Token used to authenticate to Github'
  qty_runners:
    description: 'Number of expected runners'
    default: '1'
  github_repository:
    description: 'The repository in which the runners are deployed'
    
runs:
  using: "composite"
  steps:
  - name: Install dependencies
    shell: bash
    run: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
  - name: clean up runners
    shell: python {0} 
    id: cleanup-runners
    run: |
      from github import Auth
      from github import Github
      from github import GithubException
      import os
      from time import sleep
      # Attempts to remove any offline runners - giving time for old ones to expire
      def main():
        expected_number_of_runners=os.getenv('qty_runners',1)
        github_repository=os.getenv('github_repository')
        auth = Auth.Token(os.getenv('gh_auth_token'))
        print(f'Repo name is: {github_repository}')
        g = Github(auth=auth)
        repo = g.get_repo(github_repository)
        offline_deleted=False
        qty_runners=retry_count=0
        while qty_runners!=expected_number_of_runners and retry_count < 10:
          try:
            runners = repo.get_self_hosted_runners() 
            qty_runners=runners.totalCount
            print(f'Attempt to clean up offline runners: {retry_count} - found {qty_runners} runners')
            for each_runner in runners:
              print(f'Checking runner {each_runner.name} with status {each_runner.status}')
              if each_runner.status == 'offline':
                success=repo.remove_self_hosted_runner(each_runner.id)
          except:
            print(f'Failed because {GithubException.message}')
          retry_count+=1
          sleep(10)
      if __name__ == '__main__':
        main()
    
    env:
      github_repository: ${{ inputs.github_repository }}
      gh_auth_token: ${{ inputs.gh_auth_token }}
