name: Build Docker image
description: Build, and optionally push, a Docker image

inputs:
  project:
    description: Project name
  dockerfile:
    description: Dockerfile path
    default: Dockerfile
  push:
    description: Whether to push images to the registry
    default: 'false'
  no-cache:
    description: Whether to disable Docker build cache
    default: 'false'
  pull:
    description: Whether to pull newer base image layers
    default: 'false'
  version:
    description: Version

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@1f40c72289eff860ee54a304f1438e3cff362e0a # v4.3.0
    - uses: docker/setup-buildx-action@37fe631027851001ddb9b187196cc803df7f5f0e # v4.3.0
    - uses: docker/login-action@dbcb813823bdd20940b903addbd779551569679f # v4.6.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker images
      uses: docker/build-push-action@c3c9e263c25d99ce0380d002d59b67737d91b0dc # v7.4.0
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ${{ inputs.dockerfile}}
        push: ${{ inputs.push }}
        no-cache: ${{ inputs.no-cache }}
        pull: ${{ inputs.pull }}
        provenance: false
        tags: |
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest-prod
          ghcr.io/ministryofjustice/${{ inputs.project }}:${{ inputs.version }}
