name: Build Docker image
description: Build, and optionally push, a Docker image

inputs:
  project:
    description: Project name
  dockerfile:
    description: Dockerfile path
    default: Dockerfile
  push:
    description: Whether to push images to the registry
    default: 'false'
  version:
    description: Version
  gh_auth_token:
    description: GitHub token

runs:
  using: "composite"
  steps:
    - uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4
    - uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
    - uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4.1.0
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ github.token }}

    - name: Build Docker images
      uses: docker/build-push-action@f9f3042f7e2789586610d6e8b85c8f03e5195baf # v7.2.0
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        context: .
        file: ${{ inputs.dockerfile}}
        push: ${{ inputs.push }}
        provenance: false
        tags: |
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest
          ghcr.io/ministryofjustice/${{ inputs.project }}:latest-prod
          ghcr.io/ministryofjustice/${{ inputs.project }}:${{ inputs.version }}
      env:
        GH_AUTH_TOKEN: ${{ inputs.gh_auth_token }}
