---
generic-service:
  nameOverride: hmpps-github-discovery

  replicaCount: 1 # we can start with one and do more

  image:
    repository: ghcr.io/ministryofjustice/hmpps-github-actions-runner
    tag: xxx    # override at deployment time
  # port: 8080  # Not opening a port any more

  ingress:
    enabled: false

  # Due to a bug cant disable/override the sub chart.
  # https://github.com/helm/helm/pull/12162
  # Looks like it might be fixed, so...

  livenessProbe: null
  readinessProbe: null

  # livenessProbe:
  #   httpGet:
  #     path: /ping
  #     port: 8080
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   timeoutSeconds: 5
  #   failureThreshold: 5

  # readinessProbe:
  #   httpGet:
  #     path: /ping
  #     port: 8080
  #   initialDelaySeconds: 10
  #   periodSeconds: 10
  #   timeoutSeconds: 5
  #   failureThreshold: 5

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    hmpps-github-actions-runner:
      GITHUB_REPOSITORY: "GITHUB_REPOSITORY"
      GITHUB_TOKEN: "GITHUB_TOKEN"

generic-prometheus-alerts:
  targetApplication: hmpps-github-actions-runner
