---
generic-service:
  nameOverride: hmpps-github-actions-runner

  replicaCount: 2 # enough to run e2e tests

  image:
    repository: ghcr.io/ministryofjustice/hmpps-github-actions-runner
    tag: xxx    # override at deployment time
    port: 8080

  ingress:
    enabled: false

  # Due to a bug cant disable/override the sub chart.
  # https://github.com/helm/helm/pull/12162
  # Looks like it might be fixed, so...

  livenessProbe: null

  readinessProbe:
    httpGet: null
    exec:
      command:
        - cat
        - /tmp/runner.ready
    initialDelaySeconds: 10
    periodSeconds: 10
    timeoutSeconds: 5
    failureThreshold: 5

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  env:
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name

  envFrom:
    - secretRef:
        name: hmpps-github-actions-runner

  # args:
  #   - |
  #     ORDINAL=$((0x$(echo $POD_NAME | sha1sum | head -c 2) % 4))
  #     API_KEY_VAR="NVD_API_KEY_${ORDINAL}"
  #     export NVD_API_KEY="${!API_KEY_VAR}"
  #     exec /usr/local/bin/entrypoint.sh

generic-prometheus-alerts:
  targetApplication: hmpps-github-actions-runner
