name: Build

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
      force-deploy:
        type: boolean
        default: false
    outputs:
      version:
        value: ${{ jobs.build-docker.outputs.version }}
  workflow_dispatch:
    inputs:
      push:
        description: Push images
        type: boolean
        default: false

env:
  push: ${{ inputs.push }}
  ghcr_token: ${{ secrets.GHCR_TOKEN}}

jobs:
  build-docker:
    name: Docker build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        project:
          - hmpps-github-actions-runner
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v3

      - name: Set version
        id: version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"

      - uses: actions/create-github-app-token@v1
        id: github-app-token
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        
      - name: Build Docker images
        uses: ./.github/actions/docker-build
        id: build
        with:
          project: ${{ matrix.project }}
          push: ${{ env.push }}
          version: ${{ steps.version.outputs.version }}
          gh_auth_token: ${{ steps.github-app-token.outputs.token }}