name: Build the runner Docker image

on:
  workflow_call:
    inputs:
      push:
        type: boolean
        default: false
      force-deploy:
        type: boolean
        default: false
    outputs:
      version:
        value: ${{ jobs.build-docker.outputs.version }}
  workflow_dispatch:
    inputs:
      push:
        description: Push images
        type: boolean
        default: false

env:
  push: ${{ inputs.push }}
  ghcr_token: ${{ secrets.GHCR_TOKEN}}

jobs:
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Docker build
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      - name: Set version
        id: version
        run: |
          version=$(date '+%Y-%m-%d').${{ github.run_number }}.$(echo ${{ github.sha }} | cut -c1-7)
          echo "version=$version" | tee -a "$GITHUB_OUTPUT"

      - name: Update Dockerfile FROM org
        run: sed -i.bak "s/FROM.*/FROM ghcr.io\/ministryofjustice\/hmpps-actions-runner-base:latest/" Dockerfile

      - name: GitHub app JWT and installation access token generation
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: generate-github-app-tokens
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}
        
      - name: Build Docker images
        uses: ./.github/actions/docker-build
        id: build
        with:
          project: hmpps-github-actions-runner
          push: ${{ env.push }}
          version: ${{ steps.version.outputs.version }}
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
