name: Deploy

on:
  workflow_call:
    inputs:      
      environment:
        description: The name of the environment to deploy to (dev/prod)
        type: string
        required: true
      version:
        description: The image version to deploy
        type: string
        required: true

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    environment:
      name: ${{ inputs.environment }}  
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/get-env-details
        id: env
        with:
          environment: ${{ inputs.environment }}

      - name: GitHub app JWT and installation access token generation
        uses: jamestrousdale/github-app-jwt-token@0.1.4
        id: generate-github-app-tokens
        with:
          app-id: ${{ vars.GH_APP_ID }}
          private-key: ${{ secrets.GH_APP_PRIVATE_KEY }}

      # - name: Deploy to Platform
      #   uses: ./.github/actions/cloud-platform-deploy
      #   with:
      #     environment: ${{ inputs.environment }}
      #     version: ${{ inputs.version }}
      #     api: https://${{ secrets.KUBE_CLUSTER }}
      #     cert: ${{ secrets.KUBE_CERT }}
      #     cluster: ${{ secrets.KUBE_CLUSTER }}
      #     namespace: ${{ secrets.KUBE_NAMESPACE }}
      #     token: ${{ secrets.KUBE_TOKEN }}   
      #     gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
      #     github_org: ${{ github.repository_owner }}
      #     runner_labels: ${{ vars.RUNNER_LABELS }}

      - name: Remove offline runners
        uses: ./.github/actions/runner-cleanup
        with:
          gh_auth_token: ${{ steps.generate-github-app-tokens.outputs.access-token }}
          github_org: ${{ github.repository_owner }}
      