name: Build -> Deploy pipeline

on:
  push:
    branches:
      - 'main'
      - 'fix/**'
      - 'feat/**'
      - 'feature/**'

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true      

jobs:
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      push: true
    secrets: inherit 
    
  # Deploy the pods individually so they can use separate API keys
  deploy_to_prod:
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    needs:
      - build-runner
    strategy:
      matrix:
        pod_number: [1, 2]
    with:
      environment: production
      version: ${{ needs.build-runner.outputs.version }}
      pod_number: ${{ matrix.pod_number }}
    secrets: inherit
    permissions:
      contents: read
      deployments: write
      pull-requests: write
