name: Build -> Deploy pipeline

on:
  push:
    branches:
      - '**'

  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: choice
        required: true
        options:
          - development
          - production
      version:
        description: Image version
        type: string
        required: true      

jobs:
  build-base:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ./.github/workflows/build-base.yml
    with:
      push: true
    secrets: inherit
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ./.github/workflows/build-runner.yml
    with:
      push: true
    secrets: inherit 
    
  
  # deploy_to_dev:
  #   name: Deploy to dev
  #   uses: ./.github/workflows/deploy.yml
  #   needs: build
  #   with:
  #     environment: development
  #     version: ${{ needs.build.outputs.version }}
  #   secrets: inherit

  # Only need to deploy to production nowadays
  deploy_to_prod:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    if : github.ref == 'refs/heads/main'
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    needs:
      - build-base
      - build-runner
    with:
      environment: production
      version: ${{ needs.build-runner.outputs.version }}
    secrets: inherit
