name: Build -> Deploy runner pipeline

on:
  push:
    branches:
      - 'main'
      - 'fix/**'

  schedule:
    - cron: "10 16,04 * * *" # Every 12 hours

  workflow_call:

jobs:
  build-runner:
    name: Build the latest Github Actions Runner image
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    uses: ./.github/workflows/build-runner.yml
    with:
      push: true
    secrets: inherit 
    
  # Only need to deploy to production nowadays
  deploy-to-prod:
    name: Deploy to prod
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy.yml
    with:
      environment: 'prod'
      version: 'latest-prod'
    needs:
      - build-runner
    secrets: inherit
