name: Build -> Deploy pipeline

on:
  push:
    branches:
      - 'main'
      - 'fix/**'

  workflow_dispatch:

jobs:
  build-runner:
    permissions:
      contents: read
      pull-requests: write
      deployments: write
      packages: write
    name: Build
    uses: ./.github/workflows/build-runner.yml
    with:
      push: true
    secrets: inherit 
    
  # Only need to deploy to production nowadays
  deploy_to_prod:
    permissions:
      contents: read
      deployments: write
      pull-requests: write
    if: github.ref == 'refs/heads/main'
    name: Deploy to prod
    uses: ./.github/workflows/deploy.yml
    needs:
      - build-runner
    secrets: inherit
